# Generated by Django 3.0.4 on 2020-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achievements', '0002_achievement_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='pic_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
