# Generated by Django 3.0.4 on 2020-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='descr',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_pic_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
