# Generated by Django 3.0.4 on 2020-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0002_auto_20200407_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pin_pic_link',
        ),
        migrations.AddField(
            model_name='pin',
            name='pic_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
